"""create document chunks table

Revision ID: 7c8ceecc14a5
Revises: 8f3c265b9cf5
Create Date: 2026-08-24 22:13:36.813953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7c8ceecc14a5'
down_revision: Union[str, Sequence[str], None] = '8f3c265b9cf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('document_version_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('chunk_index', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('content', mysql.LONGTEXT(), nullable=False),
    sa.Column('vector_id', sa.String(length=255), nullable=False),
    sa.Column('page_number', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('char_start', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('char_end', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_version_id', 'chunk_index', name='uq_document_chunks_version_index'),
    sa.UniqueConstraint('vector_id')
    )
    op.create_index('ix_document_chunks_version_index', 'document_chunks', ['document_version_id', 'chunk_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_chunks_version_index', table_name='document_chunks')
    op.drop_table('document_chunks')
    # ### end Alembic commands ###
