"""create incidents tables

Revision ID: ef213fbf7d55
Revises: 7c8ceecc14a5
Create Date: 2026-08-26 14:33:54.357087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ef213fbf7d55'
down_revision: Union[str, Sequence[str], None] = '7c8ceecc14a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('owner_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('knowledge_base_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('input_content', mysql.LONGTEXT(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='streaming', nullable=False),
    sa.Column('result', mysql.LONGTEXT(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_incidents_knowledge_base_created', 'incidents', ['knowledge_base_id', 'created_at'], unique=False)
    op.create_index('ix_incidents_owner_created', 'incidents', ['owner_id', 'created_at'], unique=False)
    op.create_index('ix_incidents_status', 'incidents', ['status'], unique=False)
    op.create_table('incident_citations',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('incident_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('document_chunk_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('citation_index', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'citation_index', name='uq_incident_citations_index')
    )
    op.create_index('ix_incident_citations_chunk', 'incident_citations', ['document_chunk_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_incident_citations_chunk', table_name='incident_citations')
    op.drop_table('incident_citations')
    op.drop_index('ix_incidents_status', table_name='incidents')
    op.drop_index('ix_incidents_owner_created', table_name='incidents')
    op.drop_index('ix_incidents_knowledge_base_created', table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
